apiVersion: v1
kind: Service
metadata:
  name: dvwa-service
  namespace: vulnerable-apps
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: dvwa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvwa-deployment
  namespace: vulnerable-apps
spec:
  selector:
    matchLabels:
      app: dvwa
  template:
    metadata:
      labels:
        app: dvwa
    spec:
      containers:
      - name: dvwa
        image: vulnerables/web-dvwa
        env:
        - name: MYSQL_HOST
          value: "mysql-service"
        ports:
        - containerPort: 80
