apiVersion: apps/v1
kind: Deployment
metadata:
  name: act-runner
  namespace: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: act-runner
  template:
    metadata:
      labels:
        app: act-runner
    spec:
      containers:
      - name: runner
        image: gitea/act_runner:latest
        env:
        - name: GITEA_RUNNER_REGISTRATION_TOKEN
          valueFrom:
            secretKeyRef:
              name: runner-secret
              key: token
        - name: DOCKER_HOST
          value: unix:///var/run/docker.sock
        command:
        - sh
        - -c
        - |
          if [ ! -f /data/.runner ]; then
            act_runner register --instance http://gitea-service.gitea.svc.cluster.local:3000 --token "${GITEA_RUNNER_REGISTRATION_TOKEN}" --name k3s-devsecops-runner --no-interactive
          fi
          act_runner daemon
        volumeMounts:
        - name: runner-data
          mountPath: /data
        - name: docker-socket
          mountPath: /var/run/docker.sock
      volumes:
      - name: runner-data
        hostPath:
          path: /tmp/act-runner-data
          type: DirectoryOrCreate
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
