apiVersion: v1
kind: Namespace
metadata:
  name: gitea
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-config
  namespace: gitea
data:
  app.ini: |
    APP_NAME = DevSecOps Lab Gitea
    RUN_MODE = prod
    RUN_USER = git
    WORK_PATH = /var/lib/gitea/data
    
    [repository]
    ROOT = /var/lib/gitea/data/repositories

    [database]
    DB_TYPE = sqlite3
    PATH = /var/lib/gitea/data/gitea.db
    
    [server]
    SSH_PORT = 2222
    HTTP_PORT = 3000
    ROOT_URL = http://192.168.252.10:30000/
    DISABLE_SSH = false
    
    [security]
    INSTALL_LOCK = true
    SECRET_KEY = secretkeylabdevsecops
    INTERNAL_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.secretkeylabdevsecops
    
    [oauth2]
    ENABLED = true
    JWT_SECRET = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.jwtsecretlabdevsecops
    
    [lfs]
    PATH = /var/lib/gitea/data/lfs
    JWT_SECRET = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.lfssecretlabdevsecops
    
    [service]
    DISABLE_REGISTRATION = false
    REQUIRE_SIGNIN_VIEW = false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      initContainers:
      - name: init-app-ini
        image: busybox:latest
        command: ['sh', '-c', 'cp /config-template/app.ini /var/lib/gitea/data/app.ini && chown -R 1000:1000 /var/lib/gitea/data/app.ini']
        volumeMounts:
        - name: gitea-config-ro
          mountPath: /config-template
        - name: gitea-data
          mountPath: /var/lib/gitea/data
      containers:
      - name: gitea
        image: gitea/gitea:1.21-rootless
        env:
        - name: GITEA_APP_INI
          value: /var/lib/gitea/data/app.ini
        - name: GITEA_CUSTOM
          value: /var/lib/gitea/data
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 2222
          name: ssh
        volumeMounts:
        - name: gitea-data
          mountPath: /var/lib/gitea/data
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests:
            memory: "256Mi"
            cpu: "100m"
      volumes:
      - name: gitea-data
        hostPath:
          path: /var/lib/gitea-data
          type: DirectoryOrCreate
      - name: gitea-config-ro
        configMap:
          name: gitea-config
---
apiVersion: v1
kind: Service
metadata:
  name: gitea-service
  namespace: gitea
spec:
  type: NodePort
  selector:
    app: gitea
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
    name: http
